/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Batuhan Aksoy
 */
public class _Grup_21_KanBagis_Randevuİptal extends javax.swing.JFrame {

    /**
     * Creates new form _Grup_21_KanBagis_Randevuİptal
     */
    _Grup_21_Kullanici_Girisi gelenveri = new _Grup_21_Kullanici_Girisi();
    public String gelenTC = gelenveri.TC;

    public _Grup_21_KanBagis_Randevuİptal() {
        initComponents();
        _Grup_21_Mysql_Baglanti baglanti = new _Grup_21_Mysql_Baglanti();
        jComboBox1.addItem("Lütfen Seçiniz");
        Connection baglan = baglanti.baglan();
        
        try {
            Statement stat = baglan.createStatement();
            Statement stat2 = baglan.createStatement();
            String sql = "SELECT * FROM _grup_21_kan_bagis_randevu WHERE (TCno='"+gelenTC+"')";
            String sql2 = "SELECT * FROM _grup_21_bagis_noktalari";
            ResultSet rs = stat.executeQuery(sql);
            ResultSet rs1 = stat2.executeQuery(sql2);
            while (rs.next()) {           
                    jComboBox1.addItem(rs.getString("id") + "  " + rs.getString("TCno") + "            " + rs.getString("kan_turu") + "              " + rs.getString("bagis_yeri") + "            " + rs.getString("bagis_tarih"));  
            }
            while(rs1.next())
            {
                jComboBox3.addItem(rs1.getString("adres"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Statement stat3 =baglan.createStatement();
            String sql3="SELECT * FROM _grup_21_kan_turu";
            ResultSet rs3 = stat3.executeQuery(sql3);
            while(rs3.next())
            {
              jComboBox2.addItem(rs3.getString("kan_turu"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(_Grup_21_KanBagis_Randevu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jDateChooser1.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        
        
        
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("İptal Etmek istediğiniz Randevunuzu Seçin");

        jButton1.setText("Randevuyu İptal Et");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Randevuyu Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Kan Türü");

        jLabel3.setText("Bağış Yeri");

        jLabel4.setText("Tarih");

        jButton4.setText("Güncelle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("İptal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(34, 34, 34)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        _Grup_21_Kullanici_Anasayfa kanasayfa = new _Grup_21_Kullanici_Anasayfa();
        kanasayfa.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("Lütfen Seçiniz")==false)
        {
        
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jComboBox2.setVisible(true);
        jComboBox3.setVisible(true);
        jDateChooser1.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        String randevuid;
        randevuid = jComboBox1.getSelectedItem().toString();
            randevuid= randevuid.substring(0,2);
            randevuid=randevuid.trim();
            if(randevuid.length()==2)
                randevuid= randevuid.substring(0,2);
            else
                randevuid= randevuid.substring(0,1);
            
            _Grup_21_Mysql_Baglanti baglanti = new _Grup_21_Mysql_Baglanti();
            Connection baglan=baglanti.baglan();
        try {
            Statement stat = baglan.createStatement();
            String sql = "SELECT * FROM _grup_21_kan_bagis_randevu WHERE (id='"+randevuid+"')";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next())
            {
            jComboBox2.setSelectedItem(rs.getString("kan_turu"));
            jComboBox3.setSelectedItem(rs.getString("bagis_yeri").trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(Level.SEVERE, null, ex);
        }
      } 
        else
            JOptionPane.showMessageDialog(null, "Lütfen güncellemek istediğiniz randevunuzu seçiniz");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("Lütfen Seçiniz")==false)
        {
        _Grup_21_Mysql_Baglanti baglanti = new _Grup_21_Mysql_Baglanti();
        Connection baglan = baglanti.baglan();
        boolean flag = false;
        int sonuc;
        try {
            Statement stat2 = baglan.createStatement();
            String id = jComboBox1.getSelectedItem().toString();
            id=id.substring(0,3);
            id=id.trim();
            String sql2 = "DELETE FROM _grup_21_kan_bagis_randevu WHERE (id = '" + id + "')";
            sonuc = stat2.executeUpdate(sql2);
            if (sonuc == 1) {
                flag = true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (flag == true) {
            JOptionPane.showMessageDialog(null, "Randevunuz İptal Edilmiştir");
            this.setVisible(false);
            _Grup_21_Kullanici_Anasayfa kansayfa = new _Grup_21_Kullanici_Anasayfa();
            kansayfa.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Randevunuz İptal Edilmedi");
        }
        else
            JOptionPane.showMessageDialog(null, "Lütfen silmek istediğiniz randevunuzu seçiniz");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jDateChooser1.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("Lütfen Seçiniz")==false && jComboBox2.getSelectedItem() !=null && jComboBox3.getSelectedItem() != null && jDateChooser1.getDate()!=null)
        {
        _Grup_21_Mysql_Baglanti baglanti = new _Grup_21_Mysql_Baglanti();
        Connection baglan = baglanti.baglan();
        String kan_turu = jComboBox2.getSelectedItem().toString();
        String bagis_yeri = jComboBox3.getSelectedItem().toString();
        String id=jComboBox1.getSelectedItem().toString();
        id=id.substring(0,2);
        id=id.trim();
        if(id.length()==1)
        {
            id=jComboBox1.getSelectedItem().toString();
            id=id.substring(0,1);
            
        }
            
        String bagis_tarih = jDateChooser1.getDate().toString();
        boolean flag=false;  
        int sonuc;
        
        try {
            Statement stat = baglan.createStatement();
            String sql ="UPDATE _grup_21_kan_bagis_randevu SET kan_turu='"+kan_turu+"' , bagis_yeri='"+bagis_yeri+"', bagis_tarih='"+bagis_tarih+"' WHERE (id = '"+id+"')";
            sonuc=stat.executeUpdate(sql);
            if(sonuc==1)
                flag=true;
        }catch(SQLException ex) {
            Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(flag==true)
        {
          JOptionPane.showMessageDialog(null, "Randevunuz Başarıyla Güncellenmiştir");
          this.setVisible(false);
          _Grup_21_Kullanici_Anasayfa kanasayfa = new _Grup_21_Kullanici_Anasayfa();
          kanasayfa.setVisible(true);
        }
            
            }
        else
            JOptionPane.showMessageDialog(null, "Lütfen Seçenekleri Doldurunuz");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_21_KanBagis_Randevuİptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_21_KanBagis_Randevuİptal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
